<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/31 0031
 * Time: 13:41
 */

namespace Admin\Model;


class AdminTaskListModel extends BaseModel
{
    protected $tableName = 'admin_task_list';

    public function getTaskList($num = 10)    //获取所有工单类型
    {
        $where = array(
            'state' => 1,
        );
        $count      = $this->where($where)->count();
        $page       = new \Think\Page($count,$num);
        $show       = $page->show();
        $list       = $this->where($where)->limit($page->firstRow.','.$page->listRows)->select();

        return array('page' => $show , 'list' => $list);

    }

    public function deleteAdminTask($task_id)
    {
        $where['id'] = $task_id;
        return $this->where($where)->delete();

    }
    public function PointBody($uid)        //指定工单执行人
    {

    }
    public function ReplacePerson($uid)     //转发工单，改变工单的执行人
    {

    }
    public function LevelUp()        //提升工单优先级
    {

    }
    public function LevelDown()
    {

    }
    public function CheckTask()          //审阅工单（状态改为已读）
    {

    }
    public function CompleteTask()        //工单完成
    {

    }
    public function FailTask()        //工单流单
    {

    }
    public function Create($data = '')       //创建工单
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
    public function Back()          //撤回工单
    {

    }
}